version: '3.8'

services:
  # Frontend application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:80"
    environment:
      # Ory configuration - adjust these URLs based on your setup
      - VITE_ORY_SDK_URL=http://localhost:4000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_ORY_SDK_URL=http://localhost:4000
    command: npm run dev
    profiles:
      - dev

  # Optional: Ory Kratos for local development
  # Uncomment if you want to run Ory locally
  # kratos:
  #   image: oryd/kratos:v1.0.0
  #   ports:
  #     - "4000:4433"
  #     - "4001:4434"
  #   environment:
  #     - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
  #   volumes:
  #     - kratos-sqlite:/var/lib/sqlite
  #   command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
  #   profiles:
  #     - kratos

# volumes:
#   kratos-sqlite:
